bundler_args: --without yard guard metrics benchmarks
script: "bundle exec rake spec"
rvm:
  - 2.2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
notifications:
  irc:
    channels:
      - irc.freenode.org#datamapper
    on_success: never
    on_failure: change
  email:
    recipients:
      - dan.kubb@gmail.com
    on_success: never
    on_failure: change
matrix:
  allow_failures:
    - rvm: ruby-head
